### ISSUE TITLE
Database scheme?

### ISSUE THREAD

**Issue by AndersGerner** [omkarlanghe/voucher-management-system#9]
Hi @omkarlanghe Would it be possible to get a copy of the database scheme you have used for this project so I can try it out? :)

**Comment by omkarlanghe** [comment]
@AndersGerner Unfortunately I don't have a copy of the database schema. One thing I can recommend you to try running this project on your local machine and hit APIs as per given in the .readme file. It should create the structure in the database.

**Comment by AndersGerner** [comment]
@omkarlanghe Just tested and you are right! - Thank you for such a quick response time, much appreciated!
